### PR TITLE
Server Stats + New Look

### PR DESCRIPTION
**Pull request by sk00t3r**
I hope I did this right.

### CODE REVIEW

**Comment by RdeWilde** [comment]
I would rebase to limit the number of commits ;-)

**Comment by sk00t3r** [comment]
Sure, I thought I did something wrong. Looking up how to rebase.

**Comment by RdeWilde** [comment]
Be sure to backup first ;-)

**Comment by sk00t3r** [comment]
Thank you. Total git n00b. working on that though.

**Comment by MitchellCash** [comment]
Can you please rebase over master, squash those commits and give a meaningful commit message.

I can give you instructions on how to do all if you need.

**Comment by MitchellCash** [comment]
@sk00t3r let me know if you want me to just cherry-pick your stuff and squash it down for you?

**Comment by sk00t3r** [comment]
Sorry been sick. I would love to learn how to rebase and squash commits. If you don't mind helping me out.

**Comment by MitchellCash** [comment]
@sk00t3r let's chat on slack to sort this out :)

**Comment by MitchellCash** [comment]
Closed in replace of #16, #17, #18 and #19.

**Pull request closed without merging**
