### PR TITLE
Link last block to ledger

### PR DESCRIPTION
**Pull request by RdeWilde**
Add link to ledger to make it easy to manually check last block

### CODE REVIEW

**Comment by JSponaugle** [comment]
Love this @mitchellcash When are we going to add this?

**Comment by MitchellCash** [comment]
Sorry took a long time to look at this one. I like it, however, @RdeWilde what do you think about including the block link on the already included Blocks line. I'd rather not duplication the line if possible. Like below, let me know your thoughts:

**Comment by RdeWilde** [comment]
We already talked about that :-)

It's better.

**Comment by MitchellCash** [comment]
Spoke to @RdeWilde in chat. He will be fixing this over the coming days to move the link up to the existing Blocks line.

**Comment by MitchellCash** [comment]
@RdeWilde How are you going with this one?

**Comment by RdeWilde** [comment]
@mitchellcash Not really done anything since I am no longer running a node. I'll see if I can fix it right here on Github, but will not be able to test it.

**Comment by RdeWilde** [comment]
Did new pull request.

**Pull request closed without merging**
